### PR TITLE
dep init

### LINKED ISSUE #72: Using a package/dependency manager
Is just pulled the project and tried to run the tests. But then like most golang projects some dependencies are missing and I needed to manually pull them in like this.
```go
all_test.go:16:2: cannot find package "github.com/sanity-io/litter" in any of:
```
It would be great if we could use a package/dependency manager like dep (which is going to be official) to manage dependencies and version them as it becomes easier for more people to work the this project and not have version clashes.

### PR DESCRIPTION
**Pull request by sudo-suhas**
### What does this do?

- `dep init`
- Update `.gitignore` using [github/gitignore:Go.gitignore@`master`](https://github.com/github/gitignore/blob/master/Go.gitignore) and for the `vendor` folder.

Closes #72.

### CODE REVIEW

**Comment by sudo-suhas** [comment]
@matthewmueller How do you configure semaphoreci? It would be better if CI also used `dep` for getting the dependencies. Here's some relevant documentation for using `dep` in CI - [golang/dep:docs/FAQ.md@`master`#how-do-i-use-dep-in-ci](https://github.com/golang/dep/blob/master/docs/FAQ.md#how-do-i-use-dep-in-ci).

**Comment by matthewmueller** [comment]
hey thanks for this! did you do anything special to get `dep init` working? i had troubles last time i tried.

definitely want to get `dep` going. agreed on the CI integration. i think we can just add a makefile command to semaphore to add this step. 

please give me a couple days to test this out!

**Comment by sudo-suhas** [comment]
> did you do anything special to get `dep init` working?

No, I did not have to do anything special. I installed dep using `go get`. Maybe that makes the difference?

> i think we can just add a makefile command to semaphore

Should I push a commit which updates the install step in the makefile?

> please give me a couple days to test this out!

Sure.

**Comment by sudo-suhas** [comment]
ping @matthewmueller.

**Pull request closed without merging**
